const requests = [
  {
    id: '1',
    title: 'Coffee',
    author: 'Dave Smith',
    dateCreated: '22/09',
    status: 'unfulfilled',
    description: 'put trash out',
    rewarders: 'john',
    location: 'located in building 3',
  },
  {
    id: '2',
    title: 'Pizza',
    author: 'Eric Cheese',
    dateCreated: '22/09',
    status: 'unfulfilled',
    description: 'clean the fridge',
    rewarders: 'john',
    location: 'located in building 3',
  },
  {
    id: '3',
    title: 'Cupcake',
    author: 'Dean Waters',
    dateCreated: '22/09',
    status: 'unfulfilled',
    description: 'vacumm the office room',
    rewarders: 'john',
    location: 'located in building 3',
  },
  {
    id: '4',
    title: 'Lunch',
    author: 'Jess Milk',
    dateCreated: '22/09',
    status: 'unfulfilled',
    description: 'clean room',
    rewarders: 'john',
    location: 'located in building 3',
  },
  {
    id: '5',
    title: 'Movies',
    author: 'Barry Brewster',
    dateCreated: '22/09',
    status: 'unfulfilled',
    description: 'clean room',
    rewarders: 'john',
    location: 'located in building 3',
  },
];

export default requests;
