const requests = [
	{
		id: '1',
		title: 'Coffee',
		author: 'Dave Smith',
		dateCreated: '22/09',
		status: 'unfulfilled',
		description: 'put trash out',
		rewarders: 'john',
		location: 'located in building 3',
	},
	{
		id: '2',
		title: 'Pizza',
		author: 'Eric Cheese',
		dateCreated: '22/09',
		status: 'unfulfilled',
		description: 'clean the fridge',
		rewarders: 'john',
		location: 'located in building 3',
	},
	{
		id: '3',
		title: 'Cupcake',
		author: 'Dean Waters',
		dateCreated: '22/09',
		status: 'unfulfilled',
		description: 'vacumm the office room',
		rewarders: 'john',
		location: 'located in building 3',
	},
	{
		id: '4',
		title: 'Lunch',
		author: 'Jess Milk',
		dateCreated: '22/09',
		status: 'unfulfilled',
		description: 'clean room',
		rewarders: 'john',
		location: 'located in building 3',
	},
	{
		id: '5',
		title: 'Movies',
		author: 'Barry Brewster',
		dateCreated: '22/09',
		status: 'unfulfilled',
		description: 'clean room',
		rewarders: 'john',
		location: 'located in building 3',
	},
	{
		id: '6',
		title: 'Chocolate',
		author: 'Peter Smith',
		dateCreated: '22/09',
		status: 'unfulfilled',
		description: 'wash dishes',
		rewarders: 'john',
		location: 'located in building 3',
	},
	{
		id: '7',
		title: 'Movies',
		author: 'Jacob Brewster',
		dateCreated: '22/09',
		status: 'unfulfilled',
		description: 'sweep the floor',
		rewarders: 'john',
		location: 'located in building 3',
	},
	{
		id: '8',
		title: 'Chips',
		author: 'Michael pitt',
		dateCreated: '22/09',
		status: 'unfulfilled',
		description: 'clean room',
		rewarders: 'john',
		location: 'located in building 3',
	},
	{
		id: '9',
		title: 'Fries',
		author: 'Barry Brewster',
		dateCreated: '22/09',
		status: 'unfulfilled',
		description: 'clean bathroom',
		rewarders: 'john',
		location: 'located in building 3',
	},
	{
		id: '10',
		title: 'Movies',
		author: 'Barry Brewster',
		dateCreated: '22/09',
		status: 'unfulfilled',
		description: 'clean room',
		rewarders: 'john',
		location: 'located in building 3',
	},
	{
		id: '11',
		title: 'Movies',
		author: 'Barry Brewster',
		dateCreated: '22/09',
		status: 'unfulfilled',
		description: 'clean room',
		rewarders: 'john',
		location: 'located in building 3',
	},
	{
		id: '12',
		title: 'Coffee',
		author: 'Barry Brewster',
		dateCreated: '22/09',
		status: 'unfulfilled',
		description: 'clean room',
		rewarders: 'john',
		location: 'located in building 3',
	},
];

export default requests;
